### PR TITLE
Update slip-0044.md

### PR DESCRIPTION
**Pull request by qiangkezhen**
Points Ecological Blockchain Project
LKG Alliance chain 
PEG Ecological Governance Coin

### CODE REVIEW

**Comment by qiangkezhen** [comment]
Points Ecological Blockchain Project

**Comment by qiangkezhen** [comment]
撤回

**Comment by qiangkezhen** [comment]
Submit again

**Comment by prusnak** [comment]
Please open a new PR and respect formatting (spaces and add `|` at the end of the line preceded with the right amount of spaces).

**Pull request closed without merging**
