### PR TITLE
Update slip-0044.md

### PR DESCRIPTION
**Pull request by retotrinkler**
Add EURO derivation path in imagewallet.io

### CODE REVIEW

**Comment by prusnak** [comment]
Use the first unused value, that is 254

**Comment by retotrinkler** [comment]
Done @prusnak

**Comment by prusnak** [comment]
SLIP-0044 is for cryptocurrencies with a blockchain.

**Comment by retotrinkler** [comment]
> SLIP-0044 is for cryptocurrencies with a blockchain.

The derivation path is used in context of cryptocurrencies with a blockchain.

**Comment by prusnak** [comment]
Which blockchain? Do you have 4 different blockchains for each currency?

**Pull request closed without merging**
