### PR TITLE
add Giftblock to SLIP-0044

### PR DESCRIPTION
**Pull request by martintreurnicht**

### CODE REVIEW

**Comment by prusnak** [comment]
Please add the entry to the correct place.

**Comment by martintreurnicht** [comment]
@prusnak I moved it to be just after 137

**Comment by slush0** [comment]
What's that blank record for 135?

**Comment by prusnak** [comment]
135 was (and is still) unused.

**Comment by slush0** [comment]
There's many gaps in numbering. For example 40 is unused, too. Still, there's no blank record. So should we remove that blank record or fill gaps to indicate there're unused places? In that case we should fill the table up to Rootstock testnet ;). 

Sorry for being offtopic here.

**Comment by saleemrashid** [comment]
For reference, see #47 and #48

**Pull request merged**
