### PR TITLE
SLIP-0044: Add TFUEL

### PR DESCRIPTION
**Pull request by Echolon166**
Added TFUEL

### CODE REVIEW

**Comment by prusnak** [comment]
Which wallets will use this SLIP number?

**Review by Senna96 — COMMENTED** [review]
😲 wow impressive 👏 thanks for the help 💗 I whole heartedly value your time @100% respect the time and efforts

**Review by Xuantho78 — COMMENTED** [review]
[]()

**Comment by Xuantho78** [comment]
> #1024

**Comment by Xuantho78** [comment]
#1502

**Comment by Xuantho78** [comment]
#1502

**Comment by Xuantho78** [comment]
#1502

**Review by Suria84 — APPROVED** [review]

**Pull request merged**
