### PR TITLE
Adds DeVault (DVT) to slip-0044.md

### PR DESCRIPTION
**Pull request by proteanx**
https://github.com/devaultcrypto/devault

### CODE REVIEW

**Comment by prusnak** [comment]
use the first free spot

**Comment by proteanx** [comment]
339 is what we're using already. I feel like it's pretty close to the rest of the list (we made sure to not be unreasonable). Seems like in other PRs (with #s further from list) you were only concerned with correct formatting? Hopefully we can squeeze this one in as it's not like we're asking for '7825267' like obsr etc...

**Comment by prusnak** [comment]
please provide a website with working HTTPS

**Comment by proteanx** [comment]
done

**Pull request merged**
