### PR TITLE
add Rust implementation of SLIP-0039

### PR DESCRIPTION
**Pull request by tamasblummer**
You might want to add a pointer to this implementation in Rust

### CODE REVIEW

**Comment by prusnak** [comment]
I think you should rename the class and filename to Slip39 if this is an implementation of this particular standard. Otherwise OK.

**Comment by tamasblummer** [comment]
I rather hope that you set the standard for the use of this scheme therefore not referring to by slip but by functionality. Similar to how the library refers to Wallets and not BIP32

**Comment by prusnak** [comment]
If you don't plan to change the scheme in your library then I am OK with it. Merged.

**Comment by tamasblummer** [comment]
That library has also other TREZOR compatible code. You find BIP44, BIP48, BIP84 implementations next to this. I promise not to move the linked file.

**Comment by tamasblummer** [comment]
and BIP39 of course

**Comment by prusnak** [comment]
Yeah, I checked your project, really nice!

**Pull request merged**
