### PR TITLE
XDN digitalnote 2.0

### PR DESCRIPTION
**Pull request by skironDotNet**

### CODE REVIEW

**Comment by prusnak** [comment]
use the first free number

**Comment by skironDotNet** [comment]
the rules has changed? I submitted like 5 coins and was never a problem

**Comment by prusnak** [comment]
No, it was always like this

**Comment by skironDotNet** [comment]
No way, look at those all custom selections
custom sel

Also you make invalid statement "was always like this" against other 100 coins with custom HD key reservation
how is this in order

I don't have a problem with "use the first free number" but want to know why now and not before?

**Comment by prusnak** [comment]
> I don't have a problem with "use the first free number"

Please do what I say then

**Comment by skironDotNet** [comment]
Done first available

**Pull request merged**
