### PR TITLE
New SLIP: TxRef Non-Bitcoin Display Formats Appendix

### PR DESCRIPTION
**Pull request by veleslavs**
This is an Auxiliary Appendix for https://github.com/bitcoin/bips/pull/555

### CODE REVIEW

**Comment by prusnak** [comment]
Please use Markdown format, not Mediawiki, like the rest of SLIPs.

Also please wore mork on the Introduction/Abstract section. I read it three times and still have no idea what is this SLIP about

**Comment by veleslavs** [comment]
@prusnak Thank you for your comment. I have updated the document to markdown, and have expanded the introduction.  Please don't merge this before the connected BIP is first merged.

**Comment by prusnak** [comment]
Understood. Will wait until the BIP is merged and assigned a number. Also I expect that you will change the Abstract section accordingly to contain BIP number rather than pull request number, etc.

**Comment by prusnak** [comment]
OP is MIA, closing.

**Pull request closed without merging**
