### PR TITLE
Changing 'Peer Meta Coin' name to 'Peer Coin'

### PR DESCRIPTION
**Pull request by lawmeskiviahs**

### CODE REVIEW

**Comment by prusnak** [comment]
Peercoin (PPC) is already assigned SLIP-0044 number 6.

I am not merging this so we won't confuse users which coin is which.

**Comment by urkishan** [comment]
Hi @prusnak, As the currency code for the coin is `PEER` and the name is `Peer Coin` and it is totally different blockchain.

**Comment by urkishan** [comment]
So if there is anything else we can do please let us know.

**Comment by prusnak** [comment]
You can rename your coin so that it doesn't feed on the name of another coin that has been around since 2012.

**Pull request closed without merging**
