### PR TITLE
Update slip-0044.md

### PR DESCRIPTION
**Pull request by DreamTeamCoin3**
DT3 -  DreamTeam3 - https://github.com/DreamTeamCoin3/DT3

### CODE REVIEW

**Comment by prusnak** [comment]
Use the coin's website. Not github

**Comment by DreamTeamCoin3** [comment]
> 
> 
> Use the coin's website. Not github
sorry

DT3 - DreamTeam3 https://crypto-dreamteam.com

**Comment by prusnak** [comment]
Update the pull request

**Comment by prusnak** [comment]
Drop the extra space

**Comment by DreamTeamCoin3** [comment]
done thanks ♥

**Pull request merged**
