### PR TITLE
slip-0044: Add Pi Network (minepi.com)

### PR DESCRIPTION
**Pull request by kokkalis**
Request to add Pi Network into slip-0044. 

More information about Pi Network here: http://minepi.com

### CODE REVIEW

**Comment by prusnak** [comment]
use lower case for hex

**Comment by Aao888** [comment]
派必成功，伟大的项目

**Comment by HXS8888** [comment]
很好

**Comment by AB1661205626** [comment]
恭喜

**Comment by tangpengfei2099** [comment]
44A8700A-DCFD-4600-BCB0-530EDB897D64The future is within reach.

**Comment by chris8868** [comment]
I wish pinetwork an early access to the main network, my WeChat piday2019

**Comment by chris8868** [comment]
I wish pi Network an early access to the main network❤

**Pull request merged**
