### PR TITLE
Update slip-0044.md

### PR DESCRIPTION
**Pull request by chakphanu**
remove ORT 88888,

### CODE REVIEW

**Comment by prusnak** [comment]
Reason?

**Comment by gjhiggins** [comment]
I can't seem to find the source of the wallet. There is no reference on the linked website and it doesn't show up in a GitHub search.

**Comment by gjhiggins** [comment]
Setting a precedent? A condition of successful registration is checkable source code, that condition doesn't seem to have been met in this case.

**Comment by prusnak** [comment]
Removed in 5411f34f6b8001d02dfe81def2b2597ddb5bbf7b

**Comment by A31315** [comment]
> remove ORT 88888,

**Comment by A31315** [comment]
> Reason?

**Comment by A31315** [comment]
> Removed in 5411f34f6b8001d02dfe81def2b2597ddb5bbf7b

**Comment by A31315** [comment]
> I can't seem to find the source of the wallet. There is no reference on the linked website and it doesn't show up in a GitHub search.

**Pull request closed without merging**
