### PR TITLE
Energi / NRG changes

### PR DESCRIPTION
**Pull request by andvgal**
- Restored correct Energi Mainnet 9797 registration
- Added Energi Testnet 19797 registration
- Removed never used 204 registration

### CODE REVIEW

**Comment by prusnak** [comment]
You should use 1 for testnet.

**Comment by fanatid** [comment]
Please left 204 as not available for registration, because this constant was used.

**Comment by prusnak** [comment]
@fanatid used where? Can you show me the wallet which uses 204?

**Comment by fanatid** [comment]
@prusnak uses in SLIP-044 is not enough? i.e. is assign some number and then deassign -- right?

**Comment by prusnak** [comment]
If there is no wallet using 204 for NRG I would like to keep it available.

**Comment by andvgal** [comment]
> You should use 1 for testnet (all coins). Remove the 19797 value.

A separate value is used on purpose as Energi supports both legacy (sharing Dash code) and new HD wallets. The different value is used for testing purposes in regtest/testnet.

There is at least one more coin having a separate testnet ID (37310). So, the requirement to remove one for Energi would be discriminatory.

**Comment by prusnak** [comment]
Meh

**Pull request closed without merging**
