### PR TITLE
Update slip-0044.md add HATCH #88888888

### PR DESCRIPTION
**Pull request by hatchpay**

### CODE REVIEW

**Comment by prusnak** [comment]
use the first available number

**Comment by hatchpay** [comment]
> use the first available number

Please assign the one we selected.

**Comment by prusnak** [comment]
Unless you give a really good reason I won't

**Comment by hatchpay** [comment]
> Unless you give a really good reason I won't



> Unless you give a really good reason I won't

We already used this number before we made this request.

**Comment by prusnak** [comment]
Show me the source code of the wallet using this number

**Comment by hatchpay** [comment]
> Show me the source code of the wallet using this number

{
  "coin_name": "Hatch",
  "coin_shortcut": "HATCH",
  "coin_label": "Hatch",
  "website": "https://hatch.ga",
  "github": "https://github.com/hatchpay/hatch",
  "maintainer": "Hatch Support <support@hatch.ga>",
  "curve_name": "secp256k1",
  "address_type": 76,
  "address_type_p2sh": 16,
  "maxfee_kb": 100000,
  "minfee_kb": 1000,
  "signed_message_header": "Hatch Signed Message:\n",
  "hash_genesis_block": "000000fa6116f5d6c6ce9b60bd431469e40b4fe55feeeda59e33cd2f0b863196",
  "xprv_magic": 50221816,
  "xpub_magic": 50221772,
  "xpub_magic_segwit_p2sh": null,
  "xpub_magic_segwit_native": null,
  "bech32_prefix": null,
  "cashaddr_prefix": null,
  "slip44": 88888888,
  "segwit": false,
  "decred": false,
  "fork_id": null,
  "force_bip143": false,
  "bip115": false,
  "default_fee_b": {
    "Normal": 10
  },
  "dust_limit": 5460,
  "blocktime_seconds": 150,
  "uri_prefix": "hatch",
  "min_address_length": 27,
  "max_address_length": 34,
  "bitcore": [],
  "blockbook": [],
  "negative_fee": false,
  "cooldown": 100,
  "consensus_branch_id": null,
  "confidential_assets": null
}

**Comment by prusnak** [comment]
This is not a wallet source code. Use the first available number.

**Comment by hatchpay** [comment]
> This is not a wallet source code. Use the first available number.

I provided you with a part of the source code from the wallet in which the number we selected is used. We will continue to use this number for all wallets. Please show the document on the basis of which you refuse to assign the HATCH slip-0044 number?

**Comment by prusnak** [comment]
Please show the document on the basis of which you refuse to assign the HATCH slip-0044 number?
`
Authors: Pavol Rusnak <stick@satoshilabs.com>
`

**Comment by hatchpay** [comment]
> > Please show the document on the basis of which you refuse to assign the HATCH slip-0044 number?
> 
> `Authors: Pavol Rusnak <stick@satoshilabs.com>`

Please provide a link to the document on the basis of which you require us to choose a different number. If you do not provide it, we conclude that this is your desire and nothing more.

**Comment by prusnak** [comment]
I already answered you above.

**Comment by hatchdot** [comment]
I want to draw your attention to the fact that we have provided you with 5 open repositories in which we used our BIP44, we also have 5 more repositories in which we use our BIP44 number. Hatch Core wallet already uses this BIP44 and is being integrated into other wallets. With all due respect, we are not able to choose a SLIP44 different from BIP44. Looking through the history of adding SLIP44, we find that you do not always require what you require from us, for example https://github.com/satoshilabs/slips/pull/732 The code was selected by the developer as desired. You can read the source code for Hatch Core https://github.com/hatchpay/hatch and make sure that we use this BIP44 number. You can also download binary files. Please add us SLIP44 in accordance with our BIP44 number.

**Comment by prusnak** [comment]
In all of these 5 repositories you provided, you did the change AFTER I TOLD you I am not assigning this number. If you want to get the number assigned for your coin, please send a pull request with the next available number. This is my last comment on the matter.

**Comment by hatchdot** [comment]
It is very important for us to use SLIP-0044 number equal to BIP-0044, because we have no way to change BIP-0044 for HATCH. If you carefully read the repositories, you will see that the first changes were made before submitting the SLIP-0044 application, which we immediately informed you. I also ask you to draw your attention to the fact that we created a Pull Request https://github.com/trezor/trezor-firmware/pull/520 before creating a request for receiving SLIP-0044 numbers, this proves that we had repositories with the changes made before creating a request for assigning SLIP-0044. Now requests for adding a HATCH coin to many wallets with closed source code have been created, the forms of which are already filled out. Please tell me what is the difficulty in assigning us the SLIP-0044 number equal to HATCH BIP-0044? Is it technically possible? If the answer is no, then we are ready to consider creating our firmware version for your Trezor devices with HATCH support. Will it be legal or require additional permissions from your and Trezor company?

**Pull request closed without merging**
