### PR TITLE
slip-0044:Add Nativecoin(N8V)

### PR DESCRIPTION
**Pull request by therealbityoda**
Please add Nativecoin (N8V)

### CODE REVIEW

**Comment by prusnak** [comment]
use the first available number

**Comment by therealbityoda** [comment]
> use the first available number

We Wanted number 884 as in the native community 8's are lucky numbers.

**Comment by prusnak** [comment]
I don't care, use the first available number.

**Comment by prusnak** [comment]
Also, use https in the website listing

**Comment by therealbityoda** [comment]
We re-branded from "We are satoshi" to N8V coin, and have some mobile wallet builds already using 884.

**Comment by prusnak** [comment]
Show me the source code of these mobile wallets

**Comment by therealbityoda** [comment]
The source is closed right now, as there is active development. I don't really understand the issue here, When doing slip 44 pick a number and commit.

**Comment by prusnak** [comment]
There is no problem, just pick the first available number.

**Comment by therealbityoda** [comment]
Perfect. 

884

**Pull request closed without merging**
