### PR TITLE
SLIP-0044: Add coin VALUE

### PR DESCRIPTION
**Pull request by pi-3333**
Request to add coin VALUE into slip-0044.

Wallet implementing BIP-0044 for coin VALUE (on Github) > https://github.com/pi-3333/wallet-BIP-0044

### CODE REVIEW

**Comment by prusnak** [comment]
Are coins 3333 and VALUE different coins?

**Comment by pi-3333** [comment]
Yes the coins are different.

**Comment by prusnak** [comment]
> Yes the coins are different.

Please provide websites for these coins.

**Comment by pi-3333** [comment]
3333  http://pi3333.tk/app/
VALUE  https://pi-3333.github.io

**Pull request merged**
