### PR TITLE
[slip-0044] Add ARTIS (ATS) sigma1 & tau1 networks

### PR DESCRIPTION
**Pull request by PeterTheOne**
Website: https://artis.eco
Block explorers: https://explorer.sigma1.artis.network/ http://explorer.tau1.artis.network/
chainIds: [246529](https://github.com/lab10-coop/sigma1/blob/1881ea80b475c10765d7a763ca6afd93df005b52/spec.json#L30) (sigma1) & [246785](https://github.com/lab10-coop/tau1/blob/master/spec.json#L30) (tau1)

### CODE REVIEW

**Comment by PeterTheOne** [comment]
We have been merged in https://github.com/trezor/trezor-common/pull/258 and https://github.com/ethereum-lists/chains/pull/11 .

**Comment by prusnak** [comment]
All testnet should use 1 as per SLIP-44. Remove testnet entry and keep the mainnet entry only.

**Comment by PeterTheOne** [comment]
@prusnak Hmm, but we definitely have a network running with that chainId. I removed tau1 for now.

**Comment by prusnak** [comment]
ChainID has nothing to do with SLIP44.

**Comment by PeterTheOne** [comment]
Thanks for the merge, I somehow mixed those up just now..

**Pull request merged**
