### PR TITLE
Add gbt

### PR DESCRIPTION
**Pull request by eddyCais**
新增coin type GBT(GoldBeanToken) ,网站后续补充，谢谢

### CODE REVIEW

**Comment by prusnak** [comment]
Missing URL, use the first free number

**Comment by eddyCais** [comment]
We need to register a new coin type（GBT）, the official website URL is being developed, will be added later, thanks to the merger request

**Comment by eddyCais** [comment]
> Missing URL, use the first free number



> Missing URL, use the first free number

We need to register a new coin type（GBT）, the official website URL is being developed, will be added later, thanks to the merger request

**Comment by eddyCais** [comment]
> Missing URL, use the first free number

We need to register a new coin type（GBT）, the official website URL is being developed, will be added later, thanks to the merger request

**Comment by prusnak** [comment]
Apply for the first free number once you have working website.

**Pull request closed without merging**
