### PR TITLE
added FreeCoin (FREE)

### PR DESCRIPTION
**Pull request by hungyu99**
We are busy developing a BIP44 wallet for Free Coin, and would like to request this addition to the SLIP-044 if possible please. Thanks.
Homepage: http://web.freepay.biz
GitHub: https://github.com/hungyu99/FreeCoin

### CODE REVIEW

**Comment by prusnak** [comment]
We do support only valid HTTPS links

**Comment by hungyu99** [comment]
Already updated to HTTPS link
Please check, thank you!!

**Comment by hungyu99** [comment]
> We do support only valid HTTPS links

Already updated to HTTPS link
Please check, thank you!!

**Comment by hungyu99** [comment]
Already updated to HTTPS link
Please check, thank you!!
https://github.com/satoshilabs/slips/pull/416#issuecomment-432985270

**Comment by hungyu99** [comment]
> We do support only valid HTTPS links

We are busy developing a BIP44 wallet for Free Coin, and would like to request this addition to the SLIP-044 if possible please. Thanks.
Homepage: https://web.freepay.biz
GitHub: https://github.com/hungyu99/FreeCoin

Already updated to HTTPS link
Please check, thank you!!

**Pull request merged**
