### PR TITLE
Add NewYorkCoin, GoByte, BitcoinZ, Poa, Omni

### PR DESCRIPTION
**Pull request by erasmospunk**

### CODE REVIEW

**Comment by saleemrashid** [comment]
Shouldn't Omni use the Bitcoin private keys? You need BTC in order to use OmniLayer (for transaction fees).

**Comment by prusnak** [comment]
@erasmospunk can you answer? leaving this PR unmerged creates new conflicts as new numbers are being allocated every day

**Comment by erasmospunk** [comment]
@saleemrashid @prusnak the Omni Layer is account based like Ethereum and it reuses the same key. This is the same as in Counterparty.

**Comment by saleemrashid** [comment]
@erasmospunk I understand that, but how will users pay fees? They need BTC (or LTC).

**Comment by saleemrashid** [comment]
For that matter, how will you distinguish between BTC and LTC OmniLayer?

**Pull request merged**
