### PR TITLE
Add Totem Live Accounting XTX to slip-044

### PR DESCRIPTION
**Pull request by chrisdcosta**
Totem Live Accounting is a Substrate based blockchain which already has a live public network.

* We have linked to the live network which contains the wallet implementation (Identities) in the SLIP request.

* Identities are BIP-0039 compatible and can be restored from a seed phrase + optional derivation paths.

* Restored Identities are also compatible with Parity Polkadot (DOT) and Kusama (KSM) networks

### CODE REVIEW

**Comment by prusnak** [comment]
use the first available number

**Comment by chrisdcosta** [comment]
We have already deployed our chain, is there no flexibility?

**Comment by prusnak** [comment]
I don't see how the chain is related to SLIP-44 allocation.

**Comment by prusnak** [comment]
Or do you want to use the same slip44 number as the chain_id?

**Comment by chrisdcosta** [comment]
Yes, that's the idea. We are following Parity's [Subkey](https://substrate.dev/docs/en/ecosystem/subkey#hd-derivation)  / polkadot-js implementation which also allows for a variety of extended derivation path combinations (including strings) - so it goes beyond the Bitcoin standard. 

Parity has distinguished between address generation on the Polkadot Network `354   | 0x80000162 | DOT` and their Kusama Network `434   | 0x800001b2 | KSM ` otherwise the addresses would be identical for both chains, and as we are also using the same address generation methods - it would even be identical for Totem's chain - unless we make a distinction. 

We have used this number `16181` (a variation on the golden ratio) in several other contexts as a pseudo chain Identity, so it would be nice if we could also have it here.

**Pull request merged**
