### PR TITLE
Update slip-0044.md

### PR DESCRIPTION
**Pull request by dappstore123**
ipos

### CODE REVIEW

**Comment by prusnak** [comment]
use the first available number

**Comment by dappstore123** [comment]
> use the first available number

chainid is 1122334455，what is hexa ？

**Comment by prusnak** [comment]
SLIP44 is not for chain_id. Also by choosing chain_id  bigger than 4 billions you are risking your chain won't work everywhere.

**Comment by prusnak** [comment]
If you have no idea what you are doing, let a more computer savvy person from your team do the pull request.

**Pull request closed without merging**
