### PR TITLE
Update slip-0044.md - add ION

### PR DESCRIPTION
**Pull request by cevap**
Please add ION to your BIP44 list.

Github: https://github.com/ioncoincore/ion

index   | hexa       | symbol | coin
--------|------------|--------|-----------------------------------
7567736 | 0x80737978 | ION    | [ION](https://ionomy.com/)
---

### CODE REVIEW

**Comment by prusnak** [comment]
Use the first available number

**Comment by cevap** [comment]
Is 7567736 used by some project? We already changed to this number and it is not used, why cant we use 7567736? it is free.

**Comment by prusnak** [comment]
Meh

**Comment by cevap** [comment]
@prusnak sure, but like I said this change was done more than 8 months where I even did not choose the key. Thanks for merging and I will let other know that they should use reserved, lately it did confuse me to see values which were not reserved, first I did assume that they are reserved for somebody, reading of course helps a lot :)

**Pull request merged**
