### PR TITLE
rebranded SLX to BYTZ

### PR DESCRIPTION
**Pull request by olegmitrakhovich**
SLX is now BYTZ, please change and thank you.

### CODE REVIEW

**Comment by prusnak** [comment]
Please provide the proof such rebrand happened. I don't see anything on the original website https://slate.io/

**Comment by olegmitrakhovich** [comment]
sounds good, I can guess we can update the old website with some sort of a disclaimer. Let me talk to my CTO and get back you. @prusnak

**Comment by prusnak** [comment]
@olegmitrakhovich or make a permanent redirect from old website to the new website

**Comment by olegmitrakhovich** [comment]
hey sorry I am still waiting on the response from my team...but you can see that once you click on the GitHub link here (https://slate.io/download.html) it goes to bytzcurrency GitHub with slate marked as deprecated, would that be proof enough? @prusnak

**Pull request merged**
