### PR TITLE
add Lava to slip-0044

### PR DESCRIPTION
**Pull request by jiraiyav5**

### CODE REVIEW

**Comment by prusnak** [comment]
use the first available number

**Comment by jiraiyav5** [comment]
@prusnak  Thanks !
I reback the code and use an available number !

**Comment by prusnak** [comment]
use the first available number!

**Comment by jiraiyav5** [comment]
Hi prusnak, i used the not used number 888888 ! what is your mean "first available number"?  you means that i should use index 438 ?

**Comment by prusnak** [comment]
yes

**Comment by jiraiyav5** [comment]
Hi prusnak,
    Thansk for your direction ! I hava updated Lava index to 443 (first available number). 
    Please help check and merge !

**Pull request merged**
