### PR TITLE
Update slip-0044.md

### PR DESCRIPTION
**Pull request by FelixJaraBloqs4**
Add APTA4Good to list (161803)

### CODE REVIEW

**Comment by prusnak** [comment]
Don't reformat the whole text file, just add a new line

**Comment by FelixJaraBloqs4** [comment]
> Don't reformat the whole text file, just add a new line

I sorry... that was my editor, i'll fix it.

**Comment by FelixJaraBloqs4** [comment]
Check again

**Comment by prusnak** [comment]
Use lowercase for hex

Remove extra space

**Pull request merged**
