### PR TITLE
Add BoxyCoin

### PR DESCRIPTION
**Pull request by boxycoin**
Please add Boxy when possible. (Coinomi integration) Thankyou

### CODE REVIEW

**Comment by prusnak** [comment]
215 is not 0xAF

**Comment by boxycoin** [comment]
Sorry about that, what am I doing wrong?

Example Priv key:  7q76hvo32fJvEk5rUqh6nxLjx87YXYMQ7rEHPfynrEFuH1fNBpp
Example Pub key:  XP17Pih28A1hG8bx5vqjVTMP2BNrVueA6Y
pubkey_address = 75
script_address = 18
genesis_hash = d880c4e8db4427c936d8c759b463102694366b3e2e512f7b62a946c0d39d50dd
P2PKH_VERBYTE = bytes.fromhex("4B")
P2SH_VERBYTES = [bytes.fromhex("12")]
WIF_BYTE = bytes.fromhex("CB")

**Comment by prusnak** [comment]
You added one line to our list which says 215 decadic and 0xAF hexa which are not the same values. Either change or another.

**Comment by boxycoin** [comment]
Thanks, can you please check the above and tell me what value it should be?

**Comment by prusnak** [comment]
You need to pick the value

**Pull request merged**
