### PR TITLE
Assign bip-044 number to Skycoin

### PR DESCRIPTION
**Pull request by gz-c**
BIP44 wallet support added to Skycoin:
https://github.com/skycoin/skycoin/pull/2443

Underlying library implementation (go):
https://github.com/skycoin/skycoin/tree/develop/src/cipher/bip44

### CODE REVIEW

**Comment by prusnak** [comment]
use the first available number

**Comment by gz-c** [comment]
We are using number 8000

**Comment by prusnak** [comment]
use lowercase for hex letters like the rest of the list

**Comment by prusnak** [comment]
> We are using number 8000

You merged the commit with 8000, 2 days ago. Be a good guy and change it to the first available number

**Pull request merged**
