### PR TITLE
Slip-0044 add YOU(#1010)

### PR DESCRIPTION
**Pull request by deepyu**
Add YOU to SLIP-0044(#1010)

The SLIP-0044 type is defined in code over here:

https://github.com/youchainhq/youwallet-extension/blob/master/src/common/utils.js#L55

The Website:

https://youchain.cc/

Thank you.

### CODE REVIEW

**Comment by prusnak** [comment]
Use the first available number

**Comment by deepyu** [comment]
> Use the first available number

We changed the code to 1003(first available number)，please check it again. Thank you.

**Comment by prusnak** [comment]
First available is 534 at the moment

**Comment by deepyu** [comment]
> First available is 534 at the moment

Please check it again. Thank you.

**Pull request merged**
