### PR TITLE
slip-0044: Add PLCU

### PR DESCRIPTION
**Pull request by plcudeveloper**

### CODE REVIEW

**Comment by prusnak** [comment]
Please rename PLCULTIMA to PLC Ultima which seems to be the official name

**Comment by plcudeveloper** [comment]
> Please rename PLCULTIMA to PLC Ultima which seems to be the official name

done

**Comment by prusnak** [comment]
Use `PLC Ultima` not `PLC ULTIMA`

**Comment by plcudeveloper** [comment]
> Use `PLC Ultima` not `PLC ULTIMA`
yeah, already updated :)
Thank you!

**Pull request merged**
