### PR TITLE
slip-0044:Add ELF(AELF)

### PR DESCRIPTION
**Pull request by hzz780**
Thanks

### CODE REVIEW

**Comment by prusnak** [comment]
use the first available number

**Comment by hzz780** [comment]
Hi @prusnak .
I am sorry that we are using 1616 with our blockchain.
Some existing partner wallets are using this number now.
We hope we can keep it.
Thanks.

**Comment by azheng51714** [comment]
ELF is BTC!

**Comment by hzz780** [comment]
emmmmm

azheng is one of the R&D in our partner wallet.

**Pull request merged**
