### PR TITLE
slip-0044: add CET

### PR DESCRIPTION
**Pull request by whunmr**
Add CET.

- site: https://www.coinex.org/
- testnet: 
    - https://testnet.coinex.org/
    - https://github.com/coinexchain/testnets/

- wallets:
    - https://wallet.viabtc.com/?lang=en_US
    - https://www.purewallet.org/
    - https://www.ifwallet.com/

### CODE REVIEW

**Comment by prusnak** [comment]
use the first available number

**Comment by whunmr** [comment]
OK. got it.

**Comment by whunmr** [comment]
Since our community developed the chain and wallets since several months ago.
would be good if we can use the 688. 

IF 'use the first available number' is mandatory,  we are also OK to change the PR soon.

**Comment by prusnak** [comment]
If you already use 688 we can use that.

**Comment by whunmr** [comment]
Ok, Then I'll change the PR back to 688.   Thanks @prusnak

**Pull request merged**
