### PR TITLE
Added ABBC constant

### PR DESCRIPTION
**Pull request by abbc-foundation**
New constant for ABBC coin (https://www.abbcfoundation.com/)

### CODE REVIEW

**Comment by prusnak** [comment]
use the first available number

**Comment by abbc-foundation** [comment]
Can we use 0xABBC constant? Similar to IOTA using 0x107A?

**Comment by prusnak** [comment]
No

**Comment by abbc-foundation** [comment]
Ok, understood, is 0x800001ab available?

**Comment by prusnak** [comment]
use the first available number

**Comment by abbc-foundation** [comment]
Updated to use the first available constant

**Pull request merged**
