### PR TITLE
Add Bullions Smart Chain to SLIP-44 Registry

### PR DESCRIPTION
**Pull request by devspan**
This commit adds the Bullions Smart Chain to the SLIP-44 registry with the following details:

- Chain Name: Bullions Smart Chain
- Chain ID: 8732
- SLIP-44 Code: 0x8000221C
- Native Currency: Bullions (BLN)
- RPC URL: https://rpc.bullionsx.org/
- Explorer: [Bullionscan](https://bullionscan.io/)
- Info URL: [BullionsX](https://www.bullionsx.io/)

### CODE REVIEW

**Comment by prusnak** [comment]
8732 in decimal is not 8732 in hexadecimal

so which one is correct?

**Comment by devspan** [comment]
Thank you for catching that discrepancy, @prusnak. You're absolutely right, and I apologize for the confusion in my initial commit. I've made the necessary corrections to ensure consistency, I've pushed a new commit with these corrections.

**Comment by prusnak** [comment]
> I've made the necessary corrections to ensure consistency,

not really, 8732 in hex is 221c, not 2214

**Comment by devspan** [comment]
@prusnak thank you, i hope the hex value is now correct

**Pull request merged**
