### PR TITLE
Add XDS coin

### PR DESCRIPTION
**Pull request by dangershony**

### CODE REVIEW

**Comment by prusnak** [comment]
use the first available number

**Comment by dangershony** [comment]
Ah unfortunately this number is already in use by the miners, network was launched a few month back.

**Comment by prusnak** [comment]
Not sure how the BIP44 path relates to miners.

**Comment by dangershony** [comment]
Miners use wallets for POS and derive addresses to hold coins (I should have said stakers)
Sure we can change our wallets but it will represent bigger effort so I'd just abandone this PR instead (I was not aware we should stick to added numbers).
No harm done if you won't merge like this.

**Pull request merged**
