### PR TITLE
slip-0044: add SOL

### PR DESCRIPTION
**Pull request by CriesofCarrots**
Adds SOL to registry.
We love 501 -- it looks like SOL -- so would greatly appreciate the add!

### CODE REVIEW

**Review by ayounilimited — COMMENTED** [review]
.

**Comment by FFUV** [comment]
this pull request made me lose a whole lot of money

ca: DBMkH3udBvvkbJuUPLs3vUbPkoY8tZBsnydqFdQGZSFT

**Comment by santhoshchunchu** [comment]
Please deploy this fucking coin to moon.

CA: FYdt8T5GXucuM8rTm72jNEk2iSpi74EcsmDKYQhppump

Community : https://x.com/i/communities/1973719908744843505

**Comment by santhoshchunchu** [comment]
Dont fall for other CAs. Check the one which deployed first. Right  CA: FYdt8T5GXucuM8rTm72jNEk2iSpi74EcsmDKYQhppump 

https://x.com/i/communities/1973719908744843505

**Comment by santhoshchunchu** [comment]
https://dexscreener.com/solana/WLbcRNc5C2MBeFJWf8pikHVXfx2BR2CggEUYQCWbY6X

**Pull request merged**
