### PR TITLE
Added entry for Graphene (490)

### PR DESCRIPTION
**Pull request by tohsnoom**

### CODE REVIEW

**Comment by prusnak** [comment]
use the first available number, provide URL for coin

**Comment by tohsnoom** [comment]
OK, I have updated the PR to use the first available number, and added a URL from the domain we have procured for it. This is a new project, the website is not live yet.

**Comment by prusnak** [comment]
486 is already allocated, use the number 490

**Comment by tohsnoom** [comment]
Done

**Pull request merged**
