### PR TITLE
slip-0044: add STASH

### PR DESCRIPTION
**Pull request by BeachM**

### CODE REVIEW

**Comment by prusnak** [comment]
use the first available value

**Comment by BeachM** [comment]
@prusnak sincere apologies for the out of order index. Is it possible to make an exception? in this case The reason I ask is that we have live wallets deployed already using current index.

**Comment by prusnak** [comment]
Meh, it was irresponsible to start using the value without allocating it first.

**Comment by BeachM** [comment]
Agreed. Lesson learnt for future. Thanks again.

**Pull request merged**
