### PR TITLE
slip-0173 add BNB

### PR DESCRIPTION
**Pull request by rickyyangz**
This is for the binance chain

### CODE REVIEW

**Comment by prusnak** [comment]
1) binance.org does not work
2) can you point me to the source of this coin?

**Comment by rickyyangz** [comment]
The Binance Chain is still under development but close to launch. After launch, binance.org would be open and the source code would be gradually open sourced.

**Comment by prusnak** [comment]
OK, reopen if the coin is launched and has a public source code.

**Comment by rickyyangz** [comment]
is it a must to wait for the coin launched and open sourced? actually, we have added BNB in slip-0044.
@prusnak

**Comment by prusnak** [comment]
How am I supposed to check the validity of the values if the source is not available?

**Pull request closed without merging**
