### PR TITLE
Update slip-0044.md (Adding SnowGem)

### PR DESCRIPTION
**Pull request by PerseusPolis**

### CODE REVIEW

**Comment by prusnak** [comment]
use the first available number

**Comment by PerseusPolis** [comment]
Snowgem:
Index: 1994  
Hexa: 0x800007c8

**Comment by prusnak** [comment]
use the first available number

**Comment by GreenAppers** [comment]
If you've already launched Snowgem using 1994, consider a PR adding to https://github.com/GreenAppers/slips/blob/master/slip-0044.md instead.

satoshilabs has lost legitimacy IMHO.

**Comment by prusnak** [comment]
No response

**Pull request closed without merging**
