### PR TITLE
slip-0044: add GHOST

### PR DESCRIPTION
**Pull request by akshaynexus**

### CODE REVIEW

**Comment by akshaynexus** [comment]
Any update on this pr?i see a pr opened after this pr was merged with the same number

**Comment by prusnak** [comment]
Sorry, please rework your PR to use the next available number.

**Comment by reborn1002** [comment]
@prusnak How is it determined which pull request is implemented first?

We submitted this request 4 days ago for example but the pull request that was ultimately merged in was submitted 7 hours ago by an account that is 2 days old. 

Was there any guidelines, formatting, or anything else that may have prevented our pull request from be accepted first?

**Comment by prusnak** [comment]
You just had bad luck I did not notice your PR before I merged the other one, that's all.

**Comment by prusnak** [comment]
I moved HST to 532 and assigned you 531.

**Comment by reborn1002** [comment]
Thank you!

**Pull request merged**
