### PR TITLE
Add Counos Coin. CounosX and Counos E coins

### PR DESCRIPTION
**Pull request by counos**

### CODE REVIEW

**Comment by prusnak** [comment]
I suggest using the same value for all your Counous coins. Ethereum tokens also don't have different paths for every token. Also use the first available number.

**Comment by counos** [comment]
Counos has different coins with different network, they dont have same chain and same structure.
I see that there are some free space, if I can use index 489, and  I will use it

**Comment by prusnak** [comment]
Use 489

**Comment by prusnak** [comment]
I am not allocating 20 numbers for 20 of your coins. Please make just one allocation - for 489.

**Comment by prusnak** [comment]
added in 0dc49bd1e199fcf401f41894957e63026b692694

**Pull request closed without merging**
