### PR TITLE
slip-0044: add NEAR

### PR DESCRIPTION
**Pull request by potatodepaulo**
Add NEAR coin to registry.

### CODE REVIEW

**Comment by prusnak** [comment]
use the first available number

**Comment by potatodepaulo** [comment]
Why are other numbers added at much higher increments? I don't understand this policy.

**Comment by prusnak** [comment]
Unless you have a good reason just follow the policy of using the lowest available number

**Comment by vgrichina** [comment]
@prusnak used lowest available number

**Pull request merged**
