### PR TITLE
Add unit blockchain

### PR DESCRIPTION
**Pull request by Abuzik**
Add unit to SLIP-0044

### CODE REVIEW

**Comment by prusnak** [comment]
please fix the whitespace

**Comment by Abuzik** [comment]
> please fix the whitespace
In README.md? Or in slip-0044?

**Comment by prusnak** [comment]
In the file you are editing

**Comment by Abuzik** [comment]
> In the file you are editing

Can you please tell me where? I looking for it, but I can't find any whitespaces

**Comment by Abuzik** [comment]
> In the file you are editing

I've fixed whitespaces

**Comment by Abuzik** [comment]
> In the file you are editing

Is everything ok now?

**Comment by Abuzik** [comment]
> In the file you are editing

Hope, I've made everything right😅

**Pull request merged**
