### PR TITLE
Add huobichain

### PR DESCRIPTION
**Pull request by somereason**
Hey, we want to apply a new coin type code for huobichain
As huobichain is based on muta, and it's coin type is 918, we prefer to apply 919 as our coin type code. 
Please approve, thanks

### CODE REVIEW

**Comment by prusnak** [comment]
Muta has no cointype assigned yet. Will you update your commit to add Muta too?

**Comment by somereason** [comment]
> Muta has no cointype assigned yet. Will you update your commit to add Muta too?

No, thanks, nervos will apply 918 themself. 
We just need code 919. thank you.

**Comment by prusnak** [comment]
Okay, let's wait until 918 is assigned.

**Comment by somereason** [comment]
Well, I just noticed their pull request has not updated since a month ago. I had better change my plan.

**Pull request closed without merging**
