### PR TITLE
Add CFX to slips-0044

### PR DESCRIPTION
**Pull request by yqrashawn**

### CODE REVIEW

**Comment by prusnak** [comment]
use the first available number

**Comment by yqrashawn** [comment]
Really appreciate your work on this repo and the cryptocurrency environment.

Our team has spent a lot of time deciding the number for our token. We would really appreciate if it's possible to let us use `98689`.

**Comment by yqrashawn** [comment]
Hi, @prusnak any updates?

**Comment by prusnak** [comment]
Your reason does not seem good enough. Please use the first available number.

**Comment by yqrashawn** [comment]
@prusnak updated to use the number 503

**Pull request merged**
