### PR TITLE
Fix ICON's coin type value

### PR DESCRIPTION
**Pull request by cwkwak**
ICON has used 0x80494358 for the coin type. (applied to ledger app)

### CODE REVIEW

**Comment by prusnak** [comment]
Fix the ledger app to use the correct number.

**Comment by cwkwak** [comment]
We released the ledger app about 1 year ago. Many users have already created and used keys. Could you accept my pull request?

**Comment by prusnak** [comment]
Why haven't you used the assigned number?

**Comment by prusnak** [comment]
Also, no, I am not changing the assigned number. There is no way how to determine how many applications are there which use the correct number .

**Comment by cwkwak** [comment]
1 year ago, it was not defined. One of our team members was supposed to register this number, but he missed. Recently I found out and submitted the pull request.
I’ll check with the person to register 4a where he’s used it.

**Pull request closed without merging**
