### PR TITLE
slip-0044: add coin

### PR DESCRIPTION
**Pull request by qwerity**
Add coin BIC

### CODE REVIEW

**Comment by prusnak** [comment]
website of the coin is missing

**Comment by qwerity** [comment]
I did not mention website as it is yet under development
it should be https://beincrypto.org
but now it is available at http://dev.beincrypto.org
if it is ok I will add it

**Comment by prusnak** [comment]
add  https://beincrypto.org

**Comment by qwerity** [comment]
thanks, please recheck

**Pull request merged**
