### PR TITLE
feat(slip-0044): pigeoncoin

### PR DESCRIPTION
**Pull request by michaelmcshinsky**
Submission for Pigeoncoin.
https://github.com/Pigeoncoin/pigeoncoin/blob/master/src/chainparams.cpp#L360

### CODE REVIEW

**Comment by prusnak** [comment]
Number 5 is already assigned to Dash

**Comment by michaelmcshinsky** [comment]
@prusnak 5 is not a unique id to a specific coin. This can be shared by multiple coins.

**Comment by prusnak** [comment]
We are not assigning duplicates to SLIP-0044.

**Comment by michaelmcshinsky** [comment]
Good to know. Thanks for the response, I appreciate it.

**Pull request closed without merging**
