### PR TITLE
Add QTUM

### PR DESCRIPTION
**Pull request by superbigfu**
Signed-off-by: bepal

### CODE REVIEW

**Comment by icodeface** [comment]
傻逼？

**Comment by icodeface** [comment]
hi @prusnak, Qtum doesn't use 2301 as coin type

**Comment by prusnak** [comment]
That's not good. The document says 2301 so all wallets shoulf use this
value. If there are some wallets which use wrong number, notify them to
change it to the correct one.

**Comment by prusnak** [comment]
I can remove the line, but 88 is already used by another coin.

**Comment by icodeface** [comment]
@prusnak thanks

**Comment by fanatid** [comment]
http://exodus.io/ already uses `2301`

**Comment by dooglio** [comment]
Please hold off on reverting anything. I've contacted the Qtum dev team to find out what their stance is.

**Comment by fanatid** [comment]
@prusnak even if decision will remove `2301`, I think that this number should stay in table and other coins should not take it

**Comment by qtum-neil** [comment]
Please remove 2301 as it was not made by a Qtum team member, and it does not reflect the real number used in our wallets, Qtum uses 88 as constant, an earlier request was made here: https://github.com/satoshilabs/slips/pull/120 but it was closed due to there being a duplicate.

I think duplicates should be allowed when they reflect reality.

**Comment by fanatid** [comment]
@qtum-neil thanks for confirmation :(

@prusnak can we mark `2301` as not available and put link to this issue?

**Comment by dooglio** [comment]
Can we at least add a remark into the `88` entry to show that it's also being used by Qtum?

**Pull request merged**
