### PR TITLE
Add coin type for Decred

### PR DESCRIPTION
**Pull request by coblee**

### CODE REVIEW

**Comment by prusnak** [comment]
Please amend the commit to contain uppercase hex digits like the rest of the document.

**Comment by coblee** [comment]
The rest of the document actually has lower case hex. Only the few below my
change has uppercase hex. So which should I change?

**Comment by prusnak** [comment]
Ah, have not spotted this earlier. Will fix in a separate commit. Yours is merged. Thanks

**Comment by coblee** [comment]
Thanks!

**Pull request merged**
