### PR TITLE
add Desmos

### PR DESCRIPTION
**Pull request by kwunyeung**
I know the policy is to add the lowest available number but we would like to use `852`. `852` is the international dialing code of Hong Kong and this is a project initiated in Hong Kong. We would like to have a subtle tribute to the recent on-going decentralized protest happening in Hong Kong.

### CODE REVIEW

**Comment by prusnak** [comment]
don't remove line with 853

**Comment by kwunyeung** [comment]
Oops! Sorry. It's back there now. Thanks!

**Comment by prusnak** [comment]
Please fix the link to the website. It is broken

**Comment by kwunyeung** [comment]
fixed.

**Pull request merged**
