### PR TITLE
add Elys Network testnet bech32 prefix `elys` to slip-0173.md

### PR DESCRIPTION
**Pull request by ollieottersync**
Elys Network is currently in testnet, registering the `elys` prefix here prior adding to the cosmos chain registry. Our github is  https://github.com/elys-network

email: team@elys.network
twitter: @elys_network

### CODE REVIEW

**Review by cosmic-vagabond — APPROVED** [review]
LGTM

**Comment by prusnak** [comment]
if you register `elys` for testnet, you won't be able to use `elys` for the mainnet, because we need prefixes to be different

is that what you want?

**Comment by ollieottersync** [comment]
We want to use `elys` for mainnet. We are using it for testnet as well. Is it best that we don't register at all? Or should I register it as a mainnet prefix instead now?

**Comment by prusnak** [comment]
Only mainnet

**Comment by ollieottersync** [comment]
thank you will update to change to mainnet

**Pull request closed without merging**
