### PR TITLE
slip-0044: add Hydra Token

### PR DESCRIPTION
**Pull request by vbecas**

### CODE REVIEW

**Comment by prusnak** [comment]
use the first available number

**Comment by vbecas** [comment]
Hydra team told me to use this number

**Comment by prusnak** [comment]
Well, forward them the request

**Comment by Anfauglith** [comment]
Team member here:
Sorry, but obviously other projects have not adhered to that request of yours. Also, that derivation path is already out in the open (https://github.com/Internet-of-People/mercury-rust/blob/develop/keyvault/src/secp256k1/network/hyd.rs and https://github.com/Internet-of-People/hydra-core/blob/master/packages/crypto/src/networks/mainnet/network.json) and cannot be changed anymore.

**Comment by prusnak** [comment]
Sad story

**Comment by mudlee** [comment]
I would expect a little more kindness here. Is it a deal breaker for you? If not, please accept this PR. Thanks.

**Comment by mmatk** [comment]
what a jerk behavior in  collaborative enviroment...

**Comment by mudlee** [comment]
Thank you.

**Pull request merged**
