### PR TITLE
Update slip-0044.md

### PR DESCRIPTION
**Pull request by rastislavcore**
Updating 654 for Core Blockchain

### CODE REVIEW

**Comment by prusnak** [comment]
we do not allow duplicates

use different number

**Comment by rastislavcore** [comment]
Pavol, could you please clarify your approach for resolving conflicts related to the numbers? I couldn't locate any documentation that addresses this. From what I understand, we had the number first. See reference: https://github.com/core-coin/go-core/blob/a2349aa801bc5adb984781aff45e1f3b07b38ee4/accounts/hd.go#L31

Thank you

**Comment by prusnak** [comment]
You are supposed to register the number before using it.

**Comment by rastislavcore** [comment]
Thank you for your response. I appreciate the clarification on registering the number first. However, from my examination of the provided resources and documentation, it wasn't evident that this was a required step. Perhaps we might consider updating the documentation or providing more explicit guidelines for this to avoid any future confusion.

I still believe that our initial approach had its merits, as referenced in the earlier commit. Maybe we can discuss this further to reach a common understanding?

**Comment by prusnak** [comment]
I am making no exceptions. Feel free to use the number assigned to another coin on your own, but I am not adding duplicate entries to the list.

**Comment by rastislavcore** [comment]
Thank you for clarifying that the list follows the "first come, first served" rule.

**Pull request closed without merging**
